### ISSUE TITLE
Programmable API

### ISSUE THREAD

**Issue by talentlessguy** [sinclairzx81/hammer#2]
Would be cool if Hammer exposed a public API for writing custom build chains (for example a dev server)

**Comment by sinclairzx81** [comment]
@talentlessguy Hi, have just published some updates that provide some degree of programmability. Additionally, Hammer now implements a new micro task running infrastructure to allow you setup build automation scripts using small TypeScript files. It's somewhat documented here https://github.com/sinclairzx81/hammer#task

I should provision the public API for Hammer is extremely rough at this stage and I may actually cull it in the future. I think my preference is to keep Hammer primarily as a CLI tool as it's more geared towards general project automation at the command line vs being something you would integrate programmatically into a toolchain (unless the toolchain was working via the CLI as these Hammer tasks do). For integration into existing projects, I would recommend just using `esbuild` directly.

That said, you should be able to run what's there with the following, passing valid options (see TS type hints for what's on offer, they should roughly match the CLI)

```typescript
import { hammer } from '@sinclair/hammer'

await hammer({ type: 'build', ...options })
```
Note, this is all still a work in progress, so expect bugs here and there. 

Cheers!

**Comment by talentlessguy** [comment]
@sinclairzx81 thank you for a detailed response!

this API looks good for now

**Comment by sinclairzx81** [comment]
@talentlessguy Have done a few more updates to Tasks. You can call into Hammer as before, but just keep in mind the preference is to call hammer through it's CLI. Note, the intended usage of tasks is to allow you to quickly script up automation workflows for a project. Tasks are not specifically a programmable API as one would probably imagine; it's more scripting a interface for your project that allows you to code up programmable APIs and run them from the CLI.

```typescript
// hammer.ts

import { file, folder, shell, watch, hammer } from '@sinclair/hammer'

export async function clean(dist = 'target') {
   await folder(target).delete()
}

export async function build(dist = 'target') {
    await shell(`hammer build website/index.html --dist ${dist}`)
    await file('sitemap.xml').copyTo(dist) // copy the site map
    await folder(dist).add('sitemap.xml') // another way to copy
}
```
This functionality replicates a previous [project](https://github.com/sinclairzx81/smoke-task) of mine which I've added to Hammer as I use this functionality very often (including on this project if you check `tasks.js` in the project root). In terms of offering a dedicated API, I think the general recommendation would be to use `esbuild` directly as that is what Hammer is calling into. 

Will close of this issue. Thanks for the suggestion tho!
