### ISSUE TITLE
CRLF line endings make this unusable on UNIX systems

### ISSUE THREAD

**Issue by jonahsnider** [sinclairzx81/hammer#5]
Trying to use Hammer on a UNIX system (macOS Monterey) throws this error:

```sh
$ hammer
env: node\r: No such file or directory
```

The CRLF line endings cause `env` to be unable to find `node`, instead it strips the `\n` character but leaves the `\r`.
See https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory.

The fix appears to be as easy as using LF line endings instead of CRLF.

The same issue exists in Smoke-Task.

**Comment by dirkk0** [comment]
I am using hammer on an every day basis on both Mac OSX Monterey and Linux, so what you are describing is most likely unrelated to hammer.

**Comment by jonahsnider** [comment]
Hm, I'm not sure what the underlying cause of this issue is then. I tested a few different shells (fish, zsh, bash) on the same system and all of them had the same issue.

**Comment by dirkk0** [comment]
what happens when you enter 'node -v' on a console?

**Comment by sinclairzx81** [comment]
@jonahsnider Hi! Would you be willing to submit a PR for the LF update? Unfortunately, I don't have access to OSX to test locally, but may look at setting up GH Action around this in future.

You should be able to test locally by running the following on the fresh clone of the project.

```bash
$ npm install
$ npm run install_cli       # install hammer globally
$ hammer version            # test it
```
Cheers
S

**Comment by jonahsnider** [comment]
> what happens when you enter 'node -v' on a console?

The node version gets printed. This isn't the issue, the `node` binary itself isn't even being run because `env` thinks you're trying to run `node\r`.

> @jonahsnider Hi! Would you be willing to submit a PR for the LF update?

#6
